name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Notify on failure
        if: failure()
        run: echo "Tests failed. Check the build logs."
